### PR TITLE
Fix checkbox label position in report

### PR DESCRIPTION
**Pull request by janezj**

### CODE REVIEW

**Comment by awkay** [comment]
Good find. Did you try it out in a form where the layout is linear (instead of columnar)?

**Comment by janezj** [comment]
I tried with the rad demo and it looks fine. But I am not 100%.

**Comment by awkay** [comment]
Well, it needs to be for certain. I use this plugin in production on many screens, as others do as well. I cannot accept a PR that is untested, and I do not have time to test your stuff. If you want it, please spend the time making sure it is right.

**Comment by janezj** [comment]
I know two cases with and without ro/control-layout.  I tested both.
 What do you mean by "linear" (wo control-layout)?

**Comment by awkay** [comment]
I meant in-line where the labels are beside the control instead of above it.

[] Label

vs

label
[]

but now that I say that, I don't remember if the former is ever generated by the plugin...

but this is an example:

https://fomantic-ui.com/collections/form.html#required

**Comment by janezj** [comment]
There are 4 possible combinations, the one you mentioned in the last email
is not possible in the current version, because of the toggle class.
So to implement it we have to introduce two flags: toggle? (default true)
label-top? (default false). This is the current default and backwards
compatible.

                           ::rotate?   {:type          :boolean
                                        :local?        true
                                        :label         "Pivot?"

*   :toggle? true                                        :label-top? true*
                                        :default-value false}

**Comment by janezj** [comment]
checkbox code is merge already

**Pull request closed without merging**
